export const defaultConfig = {
  notion: {
    statusProperty: 'Status',
    readyValue: 'Ready',
    publishedValue: 'Published',
    errorValue: 'Error',
    transformingValue: 'Transforming',
    publishingValue: 'Publishing',
    linkedinUrlProperty: 'LinkedIn URL',
    publishedDateProperty: 'Published Date',
    titleProperty: 'Name',
    toneProperty: 'Tone',
    tagsProperty: 'Tags',
    aiSummaryProperty: 'AI Summary',
    variantsProperty: 'Variants',
    errorLogProperty: 'Error Log',
    linkedinPostIdProperty: 'LinkedIn Post ID',
  },
  linkedin: {
    apiVersion: '202601',
    baseUrl: 'https://api.linkedin.com',
    postsEndpoint: '/rest/posts',
    authUrl: 'https://www.linkedin.com/oauth/v2/authorization',
    tokenUrl: 'https://www.linkedin.com/oauth/v2/accessToken',
    userInfoUrl: 'https://api.linkedin.com/v2/userinfo',
    scopes: ['openid', 'email', 'w_member_social'],
    oauthCallbackPort: 3456,
    maxPostLength: 3000,
    maxThreadPosts: 10,
  },
  ai: {
    model: 'claude-sonnet-4-20250514',
    geminiModel: 'gemini-2.0-flash',
    groqModel: 'llama-3.3-70b-versatile',
    maxTokens: 4096,
    defaultTone: 'professional' as const,
    availableTones: [
      'professional',
      'casual',
      'authority',
      'storytelling',
      'educational',
    ] as const,
  },
  pipeline: {
    retryAttempts: 3,
    retryDelayMs: 1000,
    retryBackoffMultiplier: 2,
    batchSize: 5,
  },
  schedule: {
    defaultCron: '0 9 * * 1-5',
    timezone: 'Europe/London',
  },
} as const;
